// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Summary {
    /**
     * Creates a new Summary instance.
     * @param {Partial<Summary>} [$$source = {}] - The source object to create the Summary.
     */
    constructor($$source = {}) {
        if (!("EventCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["EventCount"] = 0;
        }
        if (!("TraceCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TraceCount"] = 0;
        }
        if (!("FindingCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["FindingCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Summary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Summary(/** @type {Partial<Summary>} */($$parsedSource));
    }
}
