// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppLogRow {
    /**
     * Creates a new AppLogRow instance.
     * @param {Partial<AppLogRow>} [$$source = {}] - The source object to create the AppLogRow.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("DatasetID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DatasetID"] = 0;
        }
        if (!("InputFileID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["InputFileID"] = 0;
        }
        if (!("LineNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["LineNumber"] = 0;
        }
        if (!("TimestampText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TimestampText"] = "";
        }
        if (!("Severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Severity"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppLogRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppLogRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppLogRow(/** @type {Partial<AppLogRow>} */($$parsedSource));
    }
}

export class AppLogSearchPage {
    /**
     * Creates a new AppLogSearchPage instance.
     * @param {Partial<AppLogSearchPage>} [$$source = {}] - The source object to create the AppLogSearchPage.
     */
    constructor($$source = {}) {
        if (!("Lines" in $$source)) {
            /**
             * @member
             * @type {AppLogRow[]}
             */
            this["Lines"] = [];
        }
        if (!("Total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }
        if (!("NextCursor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["NextCursor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppLogSearchPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppLogSearchPage}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Lines" in $$parsedSource) {
            $$parsedSource["Lines"] = $$createField0_0($$parsedSource["Lines"]);
        }
        return new AppLogSearchPage(/** @type {Partial<AppLogSearchPage>} */($$parsedSource));
    }
}

export class DiagnosticMetricPage {
    /**
     * Creates a new DiagnosticMetricPage instance.
     * @param {Partial<DiagnosticMetricPage>} [$$source = {}] - The source object to create the DiagnosticMetricPage.
     */
    constructor($$source = {}) {
        if (!("Metrics" in $$source)) {
            /**
             * @member
             * @type {DiagnosticMetricRecord[]}
             */
            this["Metrics"] = [];
        }
        if (!("Total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }
        if (!("NextCursor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["NextCursor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticMetricPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticMetricPage}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Metrics" in $$parsedSource) {
            $$parsedSource["Metrics"] = $$createField0_0($$parsedSource["Metrics"]);
        }
        return new DiagnosticMetricPage(/** @type {Partial<DiagnosticMetricPage>} */($$parsedSource));
    }
}

export class DiagnosticMetricRecord {
    /**
     * Creates a new DiagnosticMetricRecord instance.
     * @param {Partial<DiagnosticMetricRecord>} [$$source = {}] - The source object to create the DiagnosticMetricRecord.
     */
    constructor($$source = {}) {
        if (!("DatasetID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DatasetID"] = 0;
        }
        if (!("Dimension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Dimension"] = "";
        }
        if (!("Value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Value"] = "";
        }
        if (!("EventCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["EventCount"] = 0;
        }
        if (!("CompletedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["CompletedCount"] = 0;
        }
        if (!("FailedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["FailedCount"] = 0;
        }
        if (!("DegradedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DegradedCount"] = 0;
        }
        if (!("DurationSamples" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DurationSamples"] = 0;
        }
        if (!("DurationP50MS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DurationP50MS"] = 0;
        }
        if (!("DurationP95MS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DurationP95MS"] = 0;
        }
        if (!("DurationP99MS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DurationP99MS"] = 0;
        }
        if (!("TTFTSamples" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TTFTSamples"] = 0;
        }
        if (!("TTFTP50MS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TTFTP50MS"] = 0;
        }
        if (!("TTFTP95MS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TTFTP95MS"] = 0;
        }
        if (!("TTFTP99MS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TTFTP99MS"] = 0;
        }
        if (!("RequestBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["RequestBytes"] = 0;
        }
        if (!("ResponseBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ResponseBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticMetricRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticMetricRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiagnosticMetricRecord(/** @type {Partial<DiagnosticMetricRecord>} */($$parsedSource));
    }
}

export class EventCursor {
    /**
     * Creates a new EventCursor instance.
     * @param {Partial<EventCursor>} [$$source = {}] - The source object to create the EventCursor.
     */
    constructor($$source = {}) {
        if (!("TraceKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TraceKey"] = "";
        }
        if (!("TimestampSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TimestampSeconds"] = 0;
        }
        if (!("TimestampNanoseconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TimestampNanoseconds"] = 0;
        }
        if (!("SequenceKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SequenceKey"] = "";
        }
        if (!("IngestOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["IngestOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventCursor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventCursor}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EventCursor(/** @type {Partial<EventCursor>} */($$parsedSource));
    }
}

export class EventRow {
    /**
     * Creates a new EventRow instance.
     * @param {Partial<EventRow>} [$$source = {}] - The source object to create the EventRow.
     */
    constructor($$source = {}) {
        if (!("DatasetID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DatasetID"] = 0;
        }
        if (!("SourceFileID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["SourceFileID"] = 0;
        }
        if (!("LineNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["LineNumber"] = 0;
        }
        if (!("Timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("Sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Sequence"] = 0;
        }
        if (!("IngestOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["IngestOrder"] = 0;
        }
        if (!("TraceKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TraceKey"] = "";
        }
        if (!("SchemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["SchemaVersion"] = 0;
        }
        if (!("AppSessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AppSessionID"] = "";
        }
        if (!("ProjectID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ProjectID"] = "";
        }
        if (!("TraceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TraceID"] = "";
        }
        if (!("SpanID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SpanID"] = "";
        }
        if (!("ParentSpanID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ParentSpanID"] = "";
        }
        if (!("HTTPRequestID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["HTTPRequestID"] = "";
        }
        if (!("CursorRequestID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CursorRequestID"] = "";
        }
        if (!("ConversationID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ConversationID"] = "";
        }
        if (!("TurnID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TurnID"] = "";
        }
        if (!("TurnSequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TurnSequence"] = 0;
        }
        if (!("ModelCallID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ModelCallID"] = "";
        }
        if (!("ToolCallID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ToolCallID"] = "";
        }
        if (!("Layer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Layer"] = "";
        }
        if (!("Event" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Event"] = "";
        }
        if (!("Capability" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Capability"] = "";
        }
        if (!("Operation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Operation"] = "";
        }
        if (!("Direction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Direction"] = "";
        }
        if (!("Route" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Route"] = "";
        }
        if (!("ExecutionTarget" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ExecutionTarget"] = "";
        }
        if (!("Protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Protocol"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("SemanticOutcome" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SemanticOutcome"] = "";
        }
        if (!("ImplementationState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ImplementationState"] = "";
        }
        if (!("Severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Severity"] = "";
        }
        if (!("ErrorCategory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ErrorCategory"] = "";
        }
        if (!("DurationMS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DurationMS"] = 0;
        }
        if (!("RequestBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["RequestBytes"] = 0;
        }
        if (!("ResponseBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ResponseBytes"] = 0;
        }
        if (!("DecodeError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["DecodeError"] = false;
        }
        if (!("DroppedEvents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DroppedEvents"] = 0;
        }
        if (!("SafeFieldsJSON" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SafeFieldsJSON"] = "";
        }
        if (!("PayloadRef" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PayloadRef"] = "";
        }
        if (!("Cursor" in $$source)) {
            /**
             * @member
             * @type {EventCursor}
             */
            this["Cursor"] = (new EventCursor());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventRow}
     */
    static createFrom($$source = {}) {
        const $$createField40_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Cursor" in $$parsedSource) {
            $$parsedSource["Cursor"] = $$createField40_0($$parsedSource["Cursor"]);
        }
        return new EventRow(/** @type {Partial<EventRow>} */($$parsedSource));
    }
}

export class EventSearchPage {
    /**
     * Creates a new EventSearchPage instance.
     * @param {Partial<EventSearchPage>} [$$source = {}] - The source object to create the EventSearchPage.
     */
    constructor($$source = {}) {
        if (!("Events" in $$source)) {
            /**
             * @member
             * @type {EventRow[]}
             */
            this["Events"] = [];
        }
        if (!("Total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }
        if (!("NextCursor" in $$source)) {
            /**
             * @member
             * @type {EventCursor | null}
             */
            this["NextCursor"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventSearchPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventSearchPage}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Events" in $$parsedSource) {
            $$parsedSource["Events"] = $$createField0_0($$parsedSource["Events"]);
        }
        if ("NextCursor" in $$parsedSource) {
            $$parsedSource["NextCursor"] = $$createField2_0($$parsedSource["NextCursor"]);
        }
        return new EventSearchPage(/** @type {Partial<EventSearchPage>} */($$parsedSource));
    }
}

export class FindingPage {
    /**
     * Creates a new FindingPage instance.
     * @param {Partial<FindingPage>} [$$source = {}] - The source object to create the FindingPage.
     */
    constructor($$source = {}) {
        if (!("Findings" in $$source)) {
            /**
             * @member
             * @type {FindingRow[]}
             */
            this["Findings"] = [];
        }
        if (!("Total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }
        if (!("NextCursor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["NextCursor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FindingPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FindingPage}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Findings" in $$parsedSource) {
            $$parsedSource["Findings"] = $$createField0_0($$parsedSource["Findings"]);
        }
        return new FindingPage(/** @type {Partial<FindingPage>} */($$parsedSource));
    }
}

export class FindingRow {
    /**
     * Creates a new FindingRow instance.
     * @param {Partial<FindingRow>} [$$source = {}] - The source object to create the FindingRow.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("DatasetID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DatasetID"] = 0;
        }
        if (!("Severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Severity"] = "";
        }
        if (!("SeverityRank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["SeverityRank"] = 0;
        }
        if (!("Code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Code"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }
        if (!("TraceKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TraceKey"] = "";
        }
        if (!("Count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Count"] = 0;
        }
        if (!("FirstIngestOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["FirstIngestOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FindingRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FindingRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FindingRow(/** @type {Partial<FindingRow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AppLogRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DiagnosticMetricRecord.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = EventCursor.createFrom;
const $$createType5 = EventRow.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Nullable($$createType4);
const $$createType8 = FindingRow.createFrom;
const $$createType9 = $Create.Array($$createType8);
