// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as analyze$0 from "../analyze/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "../workspace/models.js";

export class AppLogRequest {
    /**
     * Creates a new AppLogRequest instance.
     * @param {Partial<AppLogRequest>} [$$source = {}] - The source object to create the AppLogRequest.
     */
    constructor($$source = {}) {
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("after_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["after_id"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppLogRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppLogRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppLogRequest(/** @type {Partial<AppLogRequest>} */($$parsedSource));
    }
}

export class EventRequest {
    /**
     * Creates a new EventRequest instance.
     * @param {Partial<EventRequest>} [$$source = {}] - The source object to create the EventRequest.
     */
    constructor($$source = {}) {
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {workspace$0.EventCursor | null | undefined}
             */
            this["after"] = undefined;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("descending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["descending"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("after" in $$parsedSource) {
            $$parsedSource["after"] = $$createField1_0($$parsedSource["after"]);
        }
        return new EventRequest(/** @type {Partial<EventRequest>} */($$parsedSource));
    }
}

export class Initialization {
    /**
     * Creates a new Initialization instance.
     * @param {Partial<Initialization>} [$$source = {}] - The source object to create the Initialization.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = (new State());
        }
        if (!("default_input" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default_input"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["warning"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Initialization instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Initialization}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField0_0($$parsedSource["state"]);
        }
        return new Initialization(/** @type {Partial<Initialization>} */($$parsedSource));
    }
}

export class OpenRequest {
    /**
     * Creates a new OpenRequest instance.
     * @param {Partial<OpenRequest>} [$$source = {}] - The source object to create the OpenRequest.
     */
    constructor($$source = {}) {
        if (!("input" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input"] = "";
        }
        if (!("baseline" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseline"] = "";
        }
        if (!("allow_unknown_schema" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allow_unknown_schema"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenRequest(/** @type {Partial<OpenRequest>} */($$parsedSource));
    }
}

export class PayloadDocument {
    /**
     * Creates a new PayloadDocument instance.
     * @param {Partial<PayloadDocument>} [$$source = {}] - The source object to create the PayloadDocument.
     */
    constructor($$source = {}) {
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("sensitive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sensitive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PayloadDocument instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PayloadDocument}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PayloadDocument(/** @type {Partial<PayloadDocument>} */($$parsedSource));
    }
}

export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("opened" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["opened"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["input"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["baseline"] = undefined;
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {analyze$0.Summary}
             */
            this["summary"] = (new analyze$0.Summary());
        }
        if (!("has_baseline" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_baseline"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField3_0($$parsedSource["summary"]);
        }
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = workspace$0.EventCursor.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = State.createFrom;
const $$createType3 = analyze$0.Summary.createFrom;
