// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as savedquery$0 from "../savedquery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "../workspace/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseProject() {
    return $Call.ByID(2165644097);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSavedQuery(id) {
    return $Call.ByID(1786253202, id);
}

/**
 * @param {string} output
 * @returns {$CancellablePromise<void>}
 */
export function ExportReport(output) {
    return $Call.ByID(151234828, output);
}

/**
 * @returns {$CancellablePromise<$models.State>}
 */
export function GetState() {
    return $Call.ByID(2482972953).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Initialization>}
 */
export function Initialize() {
    return $Call.ByID(679172590).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} after
 * @param {number} limit
 * @returns {$CancellablePromise<workspace$0.DiagnosticMetricPage>}
 */
export function ListDiagnosticMetrics(after, limit) {
    return $Call.ByID(772884992, after, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} afterID
 * @param {number} limit
 * @returns {$CancellablePromise<workspace$0.FindingPage>}
 */
export function ListFindings(afterID, limit) {
    return $Call.ByID(1246830858, afterID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<savedquery$0.Query[]>}
 */
export function ListSavedQueries() {
    return $Call.ByID(3256723397).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {$models.OpenRequest} request
 * @returns {$CancellablePromise<$models.State>}
 */
export function OpenProject(request) {
    return $Call.ByID(3106642661, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} ingestOrder
 * @returns {$CancellablePromise<$models.PayloadDocument>}
 */
export function ReadEventPayload(ingestOrder) {
    return $Call.ByID(2736920562, ingestOrder).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {savedquery$0.Query} item
 * @returns {$CancellablePromise<savedquery$0.Query>}
 */
export function SaveQuery(item) {
    return $Call.ByID(4283080627, item).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.AppLogRequest} request
 * @returns {$CancellablePromise<workspace$0.AppLogSearchPage>}
 */
export function SearchAppLogs(request) {
    return $Call.ByID(3939274188, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.EventRequest} request
 * @returns {$CancellablePromise<workspace$0.EventSearchPage>}
 */
export function SearchEvents(request) {
    return $Call.ByID(4037264221, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectExportDirectory() {
    return $Call.ByID(2268463997);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectInputDirectory() {
    return $Call.ByID(1886359647);
}

// Private type creation functions
const $$createType0 = $models.State.createFrom;
const $$createType1 = $models.Initialization.createFrom;
const $$createType2 = workspace$0.DiagnosticMetricPage.createFrom;
const $$createType3 = workspace$0.FindingPage.createFrom;
const $$createType4 = savedquery$0.Query.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.PayloadDocument.createFrom;
const $$createType7 = workspace$0.AppLogSearchPage.createFrom;
const $$createType8 = workspace$0.EventSearchPage.createFrom;
