import {
  CloseProject,
  DeleteSavedQuery,
  ExportReport,
  GetState,
  Initialize,
  ListDiagnosticMetrics,
  ListFindings,
  ListSavedQueries,
  OpenProject,
  ReadEventPayload,
  SaveQuery,
  SearchAppLogs,
  SearchEvents,
  SelectExportDirectory,
  SelectInputDirectory,
} from "@bindings/cursor-log-analyzer/internal/gui/service.js";

export const analyzerApi = {
  closeProject: CloseProject,
  deleteSavedQuery: DeleteSavedQuery,
  exportReport: ExportReport,
  getState: GetState,
  initialize: Initialize,
  listDiagnosticMetrics: ListDiagnosticMetrics,
  listFindings: ListFindings,
  listSavedQueries: ListSavedQueries,
  openProject: OpenProject,
  readEventPayload: ReadEventPayload,
  saveQuery: SaveQuery,
  searchAppLogs: SearchAppLogs,
  searchEvents: SearchEvents,
  selectExportDirectory: SelectExportDirectory,
  selectInputDirectory: SelectInputDirectory,
};